name: update-tap

on:
  release:
    types: [created]

jobs:
  update-tap:
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formulae
        uses: dynamodb-shell-brew-pr-bot/action-homebrew-bump-formula@v3.10.0
        with:
          token: "${{ secrets.TOKEN }}"
          tap: aws/homebrew-tap
          formula: aws-ddbsh
          tag: ${{github.event.release.tag_name}}
          force: true
